:toc:
:sectnums:
:doctype: book
:toclevels: 5
:sectnumlevels: 5

[[psp_timers_eh1_ref]]
= psp_timers_eh1
The file defines timer api services for EH1 core.

|=======================
| file | psp_timers_eh1.h
| author | Nati Rapaport
| Date  |  05.05.2020
|=======================

== Definitions
|====
| *Definition* |*Value*
|D_PSP_INTERNAL_TIMER0 |1
|D_PSP_INTERNAL_TIMER1 |2
|====


==  APIs

=== pspMachineInternalTimerCounterSetup
Setup  Internal core's Timer.
[%hardbreaks]
When you call this function, you can use either one of the following defined
 values for uiTimer:
[%hardbreaks]
* *D_PSP_INTERNAL_TIMER0*
* *D_PSP_INTERNAL_TIMER1*

[source, c, subs="verbatim,quotes"]
----
void pspMachineInternalTimerCounterSetup(
  u32_t uiTimer,
  u32_t uiPeriodCycles);
----

.parameters
* *uiTimer* - Indicates which timer to setup.
* *uiPeriodCycles* - Defines timer period in cycles.

.return
* *None*

=== pspMachineInternalTimerRun
Enable incrementing timer counter(Run).
[%hardbreaks]
When you call this function, you can use either one of the following defined
 values for uiTimer:
[%hardbreaks]
* *D_PSP_INTERNAL_TIMER0*
* *D_PSP_INTERNAL_TIMER1*
[source, c, subs="verbatim,quotes"]
----
void pspMachineInternalTimerRun(u32_t uiTimer);
----

.parameters
* *uiTimer* - indicates which timer to Run

.return
* *None*

=== pspMachineInternalTimerPause
Disable incrementing timer counter.
[%hardbreaks]
When you call this function, you can use either one of the following defined
 values for uiTimer:
[%hardbreaks]
* *D_PSP_INTERNAL_TIMER0*
* *D_PSP_INTERNAL_TIMER1*
[source, c, subs="verbatim,quotes"]
----
void pspMachineInternalTimerPause(u32_t uiTimer);
----

.parameters
* *uiTimer* - indicates which timer to disable

.return
* *None*

=== pspMachineInternalTimerCounterGet
Get core internal time counter value.
[%hardbreaks]
When you call this function, you can use either one of the following defined
 values for uiTimer:
[%hardbreaks]
* *D_PSP_INTERNAL_TIMER0*
* *D_PSP_INTERNAL_TIMER1*
[source, c, subs="verbatim,quotes"]
----
u32_t pspMachineInternalTimerCounterGet(u32_t uiTimer)
----
.parameters
* *uiTimer* - Indicates which timer to get the counter value.

.return
* *u32_t* - Timer counter value.


=== pspMachineInternalTimerCompareCounterGet
Get core internal timer compare counter value.
[%hardbreaks]
When you call this function, you can use either one of the following defined
 values for uiTimer:
[%hardbreaks]
* *D_PSP_INTERNAL_TIMER0*
* *D_PSP_INTERNAL_TIMER1*
[source, c, subs="verbatim,quotes"]
----
u32_t pspMachineInternalTimerCompareCounterGet(u32_t uiTimer);
----
.parameters
* *uiTimer* - Indicates which timer to get the compare-counter value.

.return
* *u32_t* – Time compare counter value.


=== pspMachineInternalTimerEnableCountInSleepMode
Enable core internal timer counting when core in sleep mode.
[%hardbreaks]
When you call this function, you can use either one of the following defined
 values for uiTimer:
[%hardbreaks]
* *D_PSP_INTERNAL_TIMER0*
* *D_PSP_INTERNAL_TIMER1*
[source, c, subs="verbatim,quotes"]
----
void pspMachineInternalTimerEnableCountInSleepMode(u32_t uiTimer)
----
.parameters
* *uiTimer* - Indicates which timer to set up.

.return
* *None*


=== pspMachineInternalTimerDisableCountInSleepMode
Disable core internal timer counting when core in sleep mode.
[%hardbreaks]
When you call this function, you can use either one of the following defined
 values for uiTimer:
[%hardbreaks]
* *D_PSP_INTERNAL_TIMER0*
* *D_PSP_INTERNAL_TIMER1*
[source, c, subs="verbatim,quotes"]
----
void pspMachineInternalTimerDisableCountInSleepMode(u32_t uiTimer);
----
.parameters
* *uiTimer* - Indicates which timer to setup.

.return
* *None*

=== psp Machine Internal Timer Enable Count In Stall Mode
Enable core internal timer counting when core in the stall.
[%hardbreaks]
When you call this function, you can use either one of the following defined
 values for uiTimer:
[%hardbreaks]
* *D_PSP_INTERNAL_TIMER0*
* *D_PSP_INTERNAL_TIMER1*
[source, c, subs="verbatim,quotes"]
----
void pspMachineInternalTimerEnableCountInStallMode(u32_t uiTimer);
----
.parameters
* *uiTimer* - Indicates which timer to setup.

.return
* *None*


=== pspMachineInternalTimerDisableCountInStallMode
Disable core internal timer counting when core in in stall.
[%hardbreaks]
When you call this function, you can use either one of the following defined
 values for uiTimer:
[%hardbreaks]
* *D_PSP_INTERNAL_TIMER0*
* *D_PSP_INTERNAL_TIMER1*
[source, c, subs="verbatim,quotes"]
----
void pspMachineInternalTimerDisableCountInStallMode(u32_t uiTimer);
----
.parameters

* *uiTimer* - Indicates which timer to set up.
